### ISSUE TITLE
CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by jimok82** [nispok/snackbar#101]
SnackbarManager will, on occasion throw this error, regardless of whether or or not you wrap it in a try/catch. 

Looks like this should be caught from within the Snackbar class

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7095)
       at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:992)
       at android.view.View.requestLayout(View.java:18477)
       at android.view.View.requestLayout(View.java:18477)
       at android.view.View.requestLayout(View.java:18477)
       at android.view.ViewGroup.removeView(ViewGroup.java:4377)
       at com.nispok.snackbar.Snackbar.a(Snackbar.java:721)
       at com.nispok.snackbar.SnackbarManager.a(SnackbarManager.java:31)

**Comment by wmora** [comment]
Thanks, the SnackbarManager should always display a Snackbar on the main thread
