### ISSUE TITLE
IllegalStateException in AccessibilityManager.

### ISSUE THREAD

**Issue by rohans310** [nispok/snackbar#105]
This is the stack trace.

`1639-1639/com.nispok.samples.snackbar E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.nispok.samples.snackbar, PID: 1639
    java.lang.IllegalStateException: Accessibility off. Did you forget to check that?
            at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:309)
            at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:6158)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:737)
            at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5294)
            at android.view.View.sendAccessibilityEventUnchecked(View.java:5275)
            at com.nispok.snackbar.Snackbar.focusForAccessibility(Snackbar.java:838)
            at com.nispok.snackbar.Snackbar.access$1700(Snackbar.java:45)
            at com.nispok.snackbar.Snackbar$7.onAnimationEnd(Snackbar.java:809)
            at android.view.animation.Animation$3.run(Animation.java:374)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

**Comment by rohans310** [comment]
Could you please take a look at this?

**Comment by wmora** [comment]
@rohans310 which version of the lib are you using?

**Comment by rohans310** [comment]
Hey, I'm getting this on the latest sample app in master.

**Comment by wmora** [comment]
I'm not getting the error, are you getting this in one device in particular?

**Comment by Quinny898** [comment]
Also getting this with Genymotion, 4.3 device emulating

**Comment by blaze51** [comment]
making animation as false is fixing the issue.. but i need the animation also... with animation am also getting this issue

**Comment by wmora** [comment]
@blaze51 are you getting this error with the latest release, master branch or both?

**Comment by blaze51** [comment]
Latest release.

**Comment by rohans310** [comment]
Hey, sorry I was out all day. I was getting it on both kitkat and lolipop. I tested it both on emulator and actual device. Thanks for looking into it!

**Comment by Khareesh0892** [comment]
Am getting same issue with lolipop device. Am solution to solve this ?

**Comment by wmora** [comment]
I'm sorry everyone, I've had little to no time to work on this. I promise to look into it as soon as I can.

**Comment by wmora** [comment]
closed via #110
