### ISSUE TITLE
java.lang.IllegalStateException: Accessibility off. Did you forget to check that?

### ISSUE THREAD

**Issue by JamesLiAndroid** [nispok/snackbar#106]
When I try to install the exmaple on my genymotion,and I operate it,it send the error message as follow:
4-07 02:30:28.488    1379-1379/com.nispok.samples.snackbar E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.nispok.samples.snackbar, PID: 1379
    java.lang.IllegalStateException: Accessibility off. Did you forget to check that?
            at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:258)
            at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:5933)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:708)
            at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:4952)
            at android.view.View.sendAccessibilityEventUnchecked(View.java:4933)
            at com.nispok.snackbar.Snackbar.focusForAccessibility(Snackbar.java:838)
            at com.nispok.snackbar.Snackbar.access$1700(Snackbar.java:45)
            at com.nispok.snackbar.Snackbar$7.onAnimationEnd(Snackbar.java:809)
            at android.view.animation.Animation$3.run(Animation.java:374)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
I don't know how to solve it and I'm a beginner on Android development!Please tell me how to solve it.Thanks!

**Comment by wmora** [comment]
Hi, this issue has already been reported. However, I won't be able to take
a look at ut it for a few days, so please be patient :)

**Comment by patelakshay13890** [comment]
I am also facing the same issue..!!

**Comment by wmora** [comment]
dup of #105
