### ISSUE TITLE
Can't use snackbar in Runnable Method?

### ISSUE THREAD

**Issue by AruLNadhaN** [nispok/snackbar#60]
If i change this Toast to snackbar. It prompts a Error.
````java
public void showToast(final String message)
	{
		this.handler.post(new Runnable()
		{
			public void run()
			{
                  Toast.makeText(RemoteIt.this, message, Toast.LENGTH_SHORT).show();
			}
		});
	}

**Comment by wmora** [comment]
Hi, could you provide a stacktrace for this error?

**Comment by AruLNadhaN** [comment]
I used like this instead of the Toast 
```java
 SnackbarManager.show(Snackbar.with(RemoteIt.this)
                                .text(message));


Stack Trace 

01-23 14:53:30.160  19854-19854/me.arulnadhan.remoteit E/SnackbarManager﹕ Couldn't get Activity from the Snackbar's Context. Try calling #show(Snackbar, Activity) instead
    java.lang.ClassCastException: me.arulnadhan.remoteit.Client.App.RemoteIt cannot be cast to android.app.Activity
            at com.nispok.snackbar.SnackbarManager.show(SnackbarManager.java:30)
            at me.arulnadhan.remoteit.Client.App.RemoteIt$1.run(RemoteIt.java:218)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4940)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
            at dalvik.system.NativeStart.main(Native Method)

And then i tried to change the snackbar method like this 

```java
SnackbarManager.show(
                        Snackbar.with(getApplicationContext())
                                .text("Single-line snackbar"), RemoteIt.this);

**Comment by wmora** [comment]
the latest SnackbarManager now shows the Snackbar inside a Runnable. Closing this issue
